version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3307"
    expose:
      - "3307"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
